force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T - {00000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Related_Transaction_Count__c.field-meta.xml
<CustomField>
    <fullName>Related_Transaction_Count__c</fullName>
    <label>Related Transaction Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Total_Discount__c.field-meta.xml
<CustomField>
    <fullName>Total_Discount__c</fullName>
    <label>Total Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction_Line_Item__c/Transaction_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Transaction Line Item</label>
    <nameField>
        <displayFormat>TI - {00000}</displayFormat>
        <label>Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction_Line_Item__c/fields/Item_Cost__c.field-meta.xml
<CustomField>
    <fullName>Item_Cost__c</fullName>
    <label>Item Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction_Line_Item__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transaction Line Items</relationshipLabel>
    <relationshipName>Transaction_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TransactionTriggerTriggerHandlerTest.cls
/**
 * @description       : 
 * @author            : manoj543@gmail.com
 * @group             : 
 * @last modified on  : 03-23-2022
 * @last modified by  : manoj.roy@veolia.com
**/
@isTest
global class TransactionTriggerTriggerHandlerTest {


    @isTest static void testCallout() {

        Transaction__c txn = new Transaction__c();
        txn.Total_Cost__c = 250.00;
        txn.Total_Discount__c = 10;
        txn.Transaction_Date__c =  Date.today();
        txn.Related_Transaction_Count__c = 3;
        insert txn;

        List<Transaction_Line_Item__c> txnLIList = new List<Transaction_Line_Item__c>();

        for(Integer index =1 ; index <= 3; index++){
            txnLIList.add(new Transaction_Line_Item__c(Transaction__c= txn.id, Item_Cost__c = index*50));
        }

        // Set mock callout class 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        test.startTest();

        insert txnLIList;

        Test.stopTest();
    
    }

    global class MockHttpResponseGenerator implements HttpCalloutMock {

        global HTTPResponse respond(HTTPRequest req) {  
        // Create a fake response
        HttpResponse res = new HttpResponse();
        res.setHeader('Content-Type', 'application/json');
        res.setBody('{"status":"success"}');
        res.setStatusCode(201);
        return res;
    }
    }

    
}